sed -i 's/HTT_TT_X/htt_tt_0_8TeV/g' htt_tt_0_8TeV.C
sed -i 's/HTT_TT_X/htt_tt_1_8TeV/g' htt_tt_1_8TeV.C
sed -i 's/HTT_TT_X/htt_tt_2_8TeV/g' htt_tt_2_8TeV.C
sed -i 's/HHH_TT_X/htt_tt_0_8TeV/g' htt_tt_0_8TeV.C
sed -i 's/HHH_TT_X/htt_tt_1_8TeV/g' htt_tt_1_8TeV.C
sed -i 's/HHH_TT_X/htt_tt_2_8TeV/g' htt_tt_2_8TeV.C
sed -i 's/HTT_MT_X/htt_mt_0_8TeV/g' htt_mt_0_8TeV.C
sed -i 's/HTT_MT_X/htt_mt_1_8TeV/g' htt_mt_1_8TeV.C
sed -i 's/HTT_MT_X/htt_mt_2_8TeV/g' htt_mt_2_8TeV.C
sed -i 's/HTT_ET_X/htt_et_0_8TeV/g' htt_et_0_8TeV.C
sed -i 's/HTT_ET_X/htt_et_1_8TeV/g' htt_et_1_8TeV.C
sed -i 's/HTT_ET_X/htt_et_2_8TeV/g' htt_et_2_8TeV.C
