#!/bin/zsh
python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS-150707-mssm-BG-Only-30fb/plain-asimov-mhmodp-NLL/mt/" --mass-tolerance=0.2 --tolerance-denumerator-max --ggH-bbH-path="$CMSSW_BASE/src/LIMITS-150707-mssm-BG-Only-30fb/plain-asimov-ggH-bbH/" --higgs-bounds --model-masspoint="BG_Only_30fb" --expected
python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS-150707-mssm-130-15-30fb/plain-asimov-mhmodp-NLL/mt/" --mass-tolerance=0.2 --tolerance-denumerator-max --ggH-bbH-path="$CMSSW_BASE/src/LIMITS-150707-mssm-130-15-30fb/plain-asimov-ggH-bbH/" --higgs-bounds --model-masspoint="130_15_30fb_HB" --bg-path="$CMSSW_BASE/src/LIMITS-150707-mssm-BG-Only-30fb/plain-asimov-mhmodp-NLL/mt/"
python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS-150707-mssm-500-05-30fb/plain-asimov-mhmodp-NLL/mt/" --mass-tolerance=0.2 --tolerance-denumerator-max --ggH-bbH-path="$CMSSW_BASE/src/LIMITS-150707-mssm-500-05-30fb/plain-asimov-ggH-bbH/" --higgs-bounds --model-masspoint="500_05_30fb_HB" --bg-path="$CMSSW_BASE/src/LIMITS-150707-mssm-BG-Only-30fb/plain-asimov-mhmodp-NLL/mt/"
python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS-150707-mssm-500-30-30fb/plain-asimov-mhmodp-NLL/mt/" --mass-tolerance=0.2 --tolerance-denumerator-max --ggH-bbH-path="$CMSSW_BASE/src/LIMITS-150707-mssm-500-30-30fb/plain-asimov-ggH-bbH/" --higgs-bounds --model-masspoint="500_30_30fb_HB" --bg-path="$CMSSW_BASE/src/LIMITS-150707-mssm-BG-Only-30fb/plain-asimov-mhmodp-NLL/mt/"

python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS-150707-mssm-130-15-30fb/plain-asimov-mhmodp-NLL/mt/" --mass-tolerance=0.2 --tolerance-denumerator-max --ggH-bbH-path="$CMSSW_BASE/src/LIMITS-150707-mssm-130-15-30fb/plain-asimov-ggH-bbH/" --model-masspoint="130_15_30fb" --expected
python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS-150707-mssm-500-05-30fb/plain-asimov-mhmodp-NLL/mt/" --mass-tolerance=0.2 --tolerance-denumerator-max --ggH-bbH-path="$CMSSW_BASE/src/LIMITS-150707-mssm-500-05-30fb/plain-asimov-ggH-bbH/" --model-masspoint="500_05_30fb" --expected
python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS-150707-mssm-500-30-30fb/plain-asimov-mhmodp-NLL/mt/" --mass-tolerance=0.2 --tolerance-denumerator-max --ggH-bbH-path="$CMSSW_BASE/src/LIMITS-150707-mssm-500-30-30fb/plain-asimov-ggH-bbH/" --model-masspoint="500_30_30fb" --expected


#python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS150512-mssm/bbb-asimov-mhmodp-NLL/mt/" --ggH-bbH-path="$CMSSW_BASE/src/LIMITS150512-mssm/bbb-asimov-ggH-bbH/" --model-masspoint="BG_only" --light-vs-heavy
#python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS150527-mssm/bbb-asimov-mhmodp-NLL/mt/" --ggH-bbH-path="$CMSSW_BASE/src/LIMITS150527-mssm/bbb-asimov-ggH-bbH/" --model-masspoint="500_5" --light-vs-heavy
#python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS150526-mssm/bbb-asimov-mhmodp-NLL/mt/" --ggH-bbH-path="$CMSSW_BASE/src/LIMITS150526-mssm/bbb-asimov-ggH-bbH/" --model-masspoint="500_30_120_only" --forbidden-region-level=95 --light-vs-heavy
#python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS150525-mssm/bbb-asimov-mhmodp-NLL/mt/" --ggH-bbH-path="$CMSSW_BASE/src/LIMITS150525-mssm/bbb-asimov-ggH-bbH/" --model-masspoint="500_30_130_only" --light-vs-heavy
#python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS150524-mssm/bbb-asimov-mhmodp-NLL/mt/" --ggH-bbH-path="$CMSSW_BASE/src/LIMITS150524-mssm/bbb-asimov-ggH-bbH/" --model-masspoint="500_30_500_only" --light-vs-heavy
#python HiggsAnalysis/HiggsToTauTau/scripts/NLLWorkflow.py --nll-path="$CMSSW_BASE/src/LIMITS150608-mssm/bbb-asimov-mhmodp-NLL/mt/" --ggH-bbH-path="$CMSSW_BASE/src/LIMITS150608-mssm/bbb-asimov-ggH-bbH/" --model-masspoint="130_15" --light-vs-heavy